### ISSUE TITLE
Grundlegende Branchstruktur erstellen

### ISSUE THREAD

**Issue by ic21b078** [ridgizzle/MainentanceMonitor_Gruppe_A#3]
**Main branch**
Dev Branch
Hotfix Branch
Support Branch
Release Branch
feature branch

**Prefixes:**
feature/
hotfix/
support/
release/
Tag "v"

_Semantic versioning 2.0.0_

**Comment by ridgizzle** [comment]
Jedes Projektmitglied hat einen oder mehrere Branches verwendet, um dort seiner Arbeit nachgehen zu können.
