### ISSUE TITLE
Springboot-Projekt erstellen

### ISSUE THREAD

**Issue by ic21b078** [ridgizzle/MainentanceMonitor_Gruppe_A#4]
Es soll ein Start Spring Boot Projekt vir Spring Boot Initializer in INtelliJ erstellt werden.

**Einstellungen**:

java 19 + JDK 19
maven
jar Package
Name MaintenanceMonitor

Dependencies:
_Spring Boot Web_

**Comment by ridgizzle** [comment]
Wurde im Zuge des Projektbeginns angelegt
