### ISSUE TITLE
Insomnia Interface bauen

### ISSUE THREAD

**Issue by ic21b078** [ridgizzle/MainentanceMonitor_Gruppe_A#8]
Beispielhafte Darstellung des Interfaces mit dem der Service Mitarbeiter die Messages steuern kann:

![Image](https://user-images.githubusercontent.com/103936277/197599182-5d07d7c0-f46d-42c8-b221-a61ed384dbaf.png)

**Comment by ridgizzle** [comment]
Interface zum Testen der API wurde im Insomnia umgesetzt und in das Repo gepushed
